language: node_js
node_js:
  - "8.1.4"
before_install:
  - npm install
  - npm rebuild wd
services:
  - xvfb
script:
  - npm test
  - npm run test:eslint
addons:
  chrome: stable
notifications:
  email: true
sudo: false

